ToDoList2/ToDoList.UI/Controllers/ToDoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoList.UI.Enums;
using ToDoList.UI.Models;

namespace ToDoList.UI.Controllers
{
    public class ToDoListController : Controller
    {
        
        private ApplicationDbContext _dbContext;
        protected override void Dispose(bool disposing)
        {
            _dbContext.Dispose();
        }
        public ToDoListController()
        {
            _dbContext = new ApplicationDbContext();

        }

        [Authorize]
        public ActionResult Index()
        {
            var currentUser = _dbContext.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            if (currentUser != null)
            {
                var todolistitems = _dbContext.ToDoTask.Where(i=>i.ApplicationUserID == currentUser.Id).ToList();
                if(todolistitems != null)
                {
                    
                    return View(todolistitems);

                }
                else
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction("HomeController", "Index");
            }
            
        }

       
        
        public ActionResult AddTask()
        {
            var currentUser = _dbContext.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            if (currentUser != null)
            {
                
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult AddTask(ToDoTask taskToAdd)
        {
            taskToAdd.TaskStatus = Status.Active;
            taskToAdd.ApplicationUserID = _dbContext.Users.FirstOrDefault(u => u.Email == User.Identity.Name).Id;
            _dbContext.ToDoTask.Add(taskToAdd);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public ActionResult DeleteTask(ToDoTask deletedTask)
        {
            var currentUser = _dbContext.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            if (currentUser != null)
            {
                ToDoTask taskToDelete = _dbContext.ToDoTask.FirstOrDefault(t => t.Id == deletedTask.Id);
                
                _dbContext.Entry(taskToDelete).CurrentValues.SetValues(deletedTask);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult CompleteTask(ToDoTask taskCompleted)
        {
            var currentUser = _dbContext.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            if (currentUser != null)
            {
                ToDoTask taskToComplete = _dbContext.ToDoTask.FirstOrDefault(t => t.Id == taskCompleted.Id);
                _dbContext.Entry(taskToComplete).CurrentValues.SetValues(taskCompleted);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult DeleteAllCompleted()
        {
            var currentUser = _dbContext.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            if (currentUser != null)
            {
                List<ToDoTask> tasksToDelete = _dbContext.ToDoTask.Where(t => t.TaskStatus == Status.Completed).ToList();
                foreach (var task in tasksToDelete)
                {
                    var oldTask = _dbContext.ToDoTask.FirstOrDefault(t => t.Id == task.Id);
                    task.TaskStatus = Status.Deleted;

                    _dbContext.Entry(oldTask).CurrentValues.SetValues(task);

                }
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }


        }
    }
}

ToDoList2/ToDoList.UI/Views/ToDoList/AddTask.cshtml
@model ToDoList.UI.Models.ToDoTask

@{
    ViewBag.Title = "AddTask";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Task</h2>

@using (Html.BeginForm())
{<div align="center" style="width: 80%">
        <h3>New Task</h3>
        <div class="form-group">
            @Html.LabelFor(t => t.TaskName)
            @Html.TextBoxFor(t => t.TaskName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(t => t.TaskStatus)
            @Html.TextBoxFor(t => t.TaskDescription, new { @class = "form-control" })
            
        </div>
        <div class="form-group">
            @using (Html.BeginForm("AddTask", "ToDoList", FormMethod.Post))
            {
                <input type="hidden" name="Id" value="t.Id" />
                <input type="hidden" name="TaskName" value="t.TaskName" />
                <input type="hidden" name="TaskDescription" value="t.TaskDescription" />
                <input type="hidden" name="TaskStatus" value="t.TaskStatus" />
                <input type="submit" value="Submit" class="btn btn-success" />

            }
        </div>

    </div>

}

ToDoList2/ToDoList.UI/Views/ToDoList/Index.cshtml
@using ToDoList.UI.Enums
@model ICollection<ToDoList.UI.Models.ToDoTask>
@{
    
    ViewBag.Title = "ToDoList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>To Do List</h2>
<button type="button" class="btn btn-success" onclick="location.href = '@Url.Action("AddTask", "ToDoList")';return false;">Add a Task</button>

@{
    if (Model != null)
    {
        @Html.Partial("_ActiveTasks")

        @Html.Partial("_CompletedTasks")
        
    }
    else
    {
        <p>Sorry there is no items listed currently.</p>
    }
}